export const queryKeys = {
  demoContext: ["demo-context"] as const,
  modelShadowSummary: ["model-shadow-summary"] as const,
  v2Readiness: ["v2-readiness"] as const,
  v1Model: ["v1-model"] as const,
  v1Readiness: ["v1-readiness"] as const,
  demoPersonas: ["demo-personas"] as const,
  scenarios: ["scenarios"] as const,
  realtime: ["realtime"] as const,
  crowdsource: ["crowdsource"] as const,
  locations: ["locations"] as const,
  prediction: (query: unknown) => ["prediction", query] as const,
  subscriptions: (userId: string) => ["subscriptions", userId] as const,
  subscriptionPreview: (subscriptionId: string) => ["subscription-preview", subscriptionId] as const,
  subscriptionEvaluations: (subscriptionId: string) => ["subscription-evaluations", subscriptionId] as const,
  notifications: (userId: string) => ["notifications", userId] as const,
  batchPlans: (company: string) => ["batch-plans", company] as const,
};
