from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT_DIR / "data"
RUNTIME_DIR = DATA_DIR / "runtime"
DATABASE_PATH = RUNTIME_DIR / "crossborder.db"
AI_V1_ARTIFACT_PATH = RUNTIME_DIR / "models" / "wait_model_v1.joblib"
AI_V1_METADATA_PATH = DATA_DIR / "models" / "wait_model_v1.metadata.json"
AI_V1_DATASET_PATH = DATA_DIR / "history" / "port_wait_history.csv"
AI_V1_MODEL_VERSION = "synthetic-hgb-wait-v1"
AI_V1_SCHEMA_VERSION = 1
DEFAULT_SAFETY_BUFFER_MINUTES = 10
MIN_TARGET_LEAD_MINUTES = 15
MAX_TARGET_HORIZON_HOURS = 24
REALTIME_POLL_INTERVAL_SECONDS = 60
SUBSCRIPTION_PREVIEW_HORIZON_MINUTES = 180
SUBSCRIPTION_ADVANCE_REMINDER_MINUTES = 30
REPORT_DUPLICATE_WINDOW_MINUTES = 10
REPORT_EXPIRY_MINUTES = 90
REPORT_MIN_PREDICTION_SCORE = 50
REPORT_QUALITY_HIGH_THRESHOLD = 80
REPORT_QUALITY_MEDIUM_THRESHOLD = 60

# Interpretable statistical demo configuration.
HISTORY_RECENCY_HALF_LIFE_DAYS = 28
HISTORY_ADJACENT_HOUR_WEIGHT = 0.5
CROWDSOURCE_MAX_WEIGHT = 0.15
CROWDSOURCE_HORIZON_DECAY_MINUTES = 90
CONFIDENCE_LEVEL = 0.90
MIN_STANDARD_DEVIATION_MINUTES = 3.0
TREND_UNCERTAINTY_FACTOR = 0.35
EVENT_IMPACT_MULTIPLIERS = {
    "low": 1.05,
    "medium": 1.12,
    "high": 1.20,
}
MAX_COMBINED_EVENT_MULTIPLIER = 1.35
RISK_MEDIUM_THRESHOLD_PERCENT = 15
RISK_HIGH_THRESHOLD_PERCENT = 35
MODEL_VERSION = "time-weighted-statistical-demo-v2"
BALANCED_RISK_WEIGHT = 1.5
BALANCED_COST_WEIGHT = 0.12
