from pathlib import Path

from .calibration import CALIBRATION_POLICY


ROOT_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT_DIR / "data"
RUNTIME_DIR = DATA_DIR / "runtime"
DATABASE_PATH = RUNTIME_DIR / "crossborder.db"
AI_V1_ARTIFACT_PATH = RUNTIME_DIR / "models" / "wait_model_v1.joblib"
AI_V1_METADATA_PATH = DATA_DIR / "models" / "wait_model_v1.metadata.json"
AI_V1_DATASET_PATH = DATA_DIR / "history" / "port_wait_history.csv"
AI_V1_MODEL_VERSION = "synthetic-hgb-wait-v1"
AI_V1_SCHEMA_VERSION = 1
AI_V2_ARTIFACT_PATH = RUNTIME_DIR / "models" / "wait_model_v2.joblib"
AI_V2_METADATA_PATH = DATA_DIR / "models" / "wait_model_v2.metadata.json"
AI_V2_DATASET_PATH = RUNTIME_DIR / "training_snapshots" / "scenario_wait_history_v2.csv"
AI_V2_DATASET_METADATA_PATH = RUNTIME_DIR / "training_snapshots" / "scenario_wait_history_v2.metadata.json"
AI_V2_TRAFFIC_SNAPSHOT_PATH = DATA_DIR / "history" / "public_port_traffic_daily.csv"
AI_V2_TRAFFIC_METADATA_PATH = DATA_DIR / "history" / "public_port_traffic_daily.metadata.json"
SHENZHEN_REFERENCE_PATH = DATA_DIR / "history" / "shenzhen_port_reference.json"
AI_V2_MODEL_VERSION = "public-traffic-transparent-hgb-v2.2"
AI_V2_SCHEMA_VERSION = 4
DEFAULT_SAFETY_BUFFER_MINUTES = 10
MIN_TARGET_LEAD_MINUTES = 15
MAX_TARGET_HORIZON_HOURS = 24 * 14
REALTIME_POLL_INTERVAL_SECONDS = 60
SUBSCRIPTION_PREVIEW_HORIZON_MINUTES = 180
SUBSCRIPTION_ADVANCE_REMINDER_MINUTES = 30
REPORT_DUPLICATE_WINDOW_MINUTES = 10
REPORT_EXPIRY_MINUTES = 90
REPORT_MIN_PREDICTION_SCORE = 50
REPORT_QUALITY_HIGH_THRESHOLD = 80
REPORT_QUALITY_MEDIUM_THRESHOLD = 60

# Interpretable statistical demo configuration.
HISTORY_RECENCY_HALF_LIFE_DAYS = 28
HISTORY_ADJACENT_HOUR_WEIGHT = 0.5
CROWDSOURCE_MAX_WEIGHT = CALIBRATION_POLICY.crowdsource_pair_cap
CROWDSOURCE_HORIZON_DECAY_MINUTES = 720
CONFIDENCE_LEVEL = 0.90
MIN_STANDARD_DEVIATION_MINUTES = 3.0
TREND_UNCERTAINTY_FACTOR = 0.35
EVENT_IMPACT_MULTIPLIERS = CALIBRATION_POLICY.recurring_event_multipliers
MAX_COMBINED_EVENT_MULTIPLIER = CALIBRATION_POLICY.recurring_event_cap
SCENARIO_WEATHER_MULTIPLIERS = CALIBRATION_POLICY.scenario_weather_multipliers
SCENARIO_HOLIDAY_MULTIPLIER = CALIBRATION_POLICY.scenario_holiday_multiplier
SCENARIO_EVENT_MULTIPLIERS = CALIBRATION_POLICY.scenario_event_multipliers
SCENARIO_MAX_MULTIPLIER = CALIBRATION_POLICY.scenario_cap
RISK_MEDIUM_THRESHOLD_PERCENT = 15
RISK_HIGH_THRESHOLD_PERCENT = 35
MODEL_VERSION = "time-weighted-statistical-demo-v2"
BALANCED_RISK_WEIGHT = 1.5
BALANCED_COST_WEIGHT = 0.12
